### More indexing and slicing ... 2022 0624 CJH
https://stackoverflow.com/questions/509211/understanding-slicing

#### check out the ASCII art below for indexing vs slicing insights
* think of indexing as pulling out an element in that positions
* think of slicing as returning the sub-list between corners

In [110]:
p = ['P','y','t','h','o','n']
# Why the two sets of numbers:
# indexing gives items, not lists
print(f'p[0] is {p[0]}')
print(f'p[5] is {p[5]}')

# Slicing gives lists
print(f'p[0:1] is {p[0:1]}')
print(f'p[0:2] is {p[0:2]}')

p[0] is P
p[5] is n
p[0:1] is ['P']
p[0:2] is ['P', 'y']


#### list out all the shortcuts for x[low:high:stride] 

In [112]:
x = [chr(i) for i in range(97, 110)]  # 97-123 are all the letters
x

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']

In [118]:
my_slice = slice(1,5,1)
my_slice

slice(1, 5, 1)

In [119]:
x[my_slice]

['b', 'c', 'd', 'e']

#### striding backwards changes things a bit
* easy way to reverse a list on the fly

---
How did this change with numpy?

In [120]:
import numpy as np

In [124]:
gray_array = np.zeros([4,4])
gray_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [127]:
gray_array[ 3, 2 ] = 1
gray_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [138]:
gray_array = np.zeros([4,4])
gray_array[ : , :: ] = 1
gray_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])